version: 2

builds:
  - main: ./cmd/demod
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: darwin
        formats:
          - zip

changelog:
  sort: asc
