[tools]
go = "1.26.2"
goreleaser = "2.15.4"
"golangci-lint" = "2.12.2"

[tasks.build]
run = "go build ./cmd/demod/"

[tasks.test]
run = "go test ./..."

[tasks.lint]
run = "golangci-lint run"

[tasks.release-check]
run = "goreleaser check"

[tasks.release-snapshot]
run = "goreleaser release --snapshot --clean"
